modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="sydsutils"
version="1.0.0"
displayName="Syd's Utils"
credits="Created by Sydney"
displayURL="https://sydneym.dev"
authors="Sydney"
description='''
An all in one sort of mod
'''

[[dependencies.sydsutils]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"


[[dependencies.sydsutils]]
    modId="net.syd.core"
    mandatory=true
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"


